name: pre-commit
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}\
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: "x64"

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}-

      - uses: pre-commit/action@v2.0.0
        continue-on-error: true


      - name: Commit changes
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_PASSWORD: ${{ secrets.GH_PASSWORD }}
        run: |
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            git remote set-url origin https://${GH_USERNAME}:${GH_PASSWORD}@github.com/${GITHUB_REPOSITORY}.git
            git checkout -B ${{ github.ref }}
            git pull origin ${{ github.ref }}
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "pre-commit"
            git push origin ${{ github.ref }}
          fi
