name: pre-commit
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv

    strategy:
      fail-fast: false
      matrix:
        config:
        - {name: 'commit', continue: true}
        - {name: 'check', continue: false}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Check Ubuntu version
        run: |
          echo "UBUNTU_VERSION=`grep DISTRIB_RELEASE /etc/lsb-release | sed 's/.*=//g'`" >> $GITHUB_ENV

      - name: Cache R packages
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{env.UBUNTU_VERSION}}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{env.UBUNTU_VERSION}}-renv-

      - name: Set up R
        id: setup-r
        run: |
          install.packages('renv')
          renv::restore()
          renv::install('docopt')
          renv::install('styler')
          renv::install('git2r')
          renv::install('lintr')
        shell: sudo Rscript {0}

      - name: Cache pre-commit
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}-

      - uses: pre-commit/action@v2.0.0
        continue-on-error: ${{ matrix.config.continue }}

      - name: Commit files
        if: ${{ matrix.config.continue }}
        run: |
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git checkout -- .github/workflows
            git commit -m "pre-commit" -a
          fi

      - name: Push changes
        if: ${{ matrix.config.continue }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
