name: Run Tests

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: ${{ matrix.config.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {name: 'current', os: ubuntu-latest, python: '3.8' }
        - {name: 'prev', os: ubuntu-latest, python: '3.7' }
        - {name: 'old', os: ubuntu-latest, python: '3.6' }

    steps:
    - uses: actions/checkout@v2
    
    - name: Install system dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libhdf5-dev pandoc gfortran libblas-dev liblapack-dev libedit-dev llvm-dev
    
    - name: Install Singularity
      uses: eWaterCycle/setup-singularity@v3
      with:
        singularity-version: 3.6.1
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: ${{ matrix.config.python }}

    - name: Install package & dependencies
      run: |
        pip install -U .
        python -c "import openproblems"
        pip install -U .[test]
        
    - name: Linting
      run: |
        black . --check --diff --exclude=website
    
    - name: Build docker container # can snakemake do this?
      run: |
        docker build -f docker/openproblems/Dockerfile -t singlecellopenproblems/openproblems .
        docker build -f docker/openproblems-r-base/Dockerfile -t singlecellopenproblems/openproblems-r-base .
    
    - name: Run tests
      run: |
        nose2 openproblems -v
    
    - name: Upload check results on fail
      if: failure()
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.config.name }}_results
        path: check
