name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: ${{ matrix.config.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: false
      matrix:
        config:
        - {name: 'current', os: ubuntu-latest, python: '3.8' }
        - {name: 'prev', os: ubuntu-latest, python: '3.7' }
        - {name: 'old', os: ubuntu-latest, python: '3.6' }

    steps:
    - uses: actions/checkout@v2

    - name: Install system dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libhdf5-dev pandoc gfortran libblas-dev liblapack-dev libedit-dev llvm-dev

    - name: Install Singularity
      uses: eWaterCycle/setup-singularity@v5
      with:
        singularity-version: 3.6.1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python }}

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}

    - name: Install package & dependencies
      run: |
        pip install -U pip wheel setuptools
        pip install -U .[test]
        python -c "import openproblems"

    - name: Cache Singularity images
      uses: actions/cache@v2
      with:
        path: ~/.singularity
        key: ${{ env.pythonLocation }}-${{ hashFiles('**/.docker_push') }}

    - name: Run tests
      run: |
        nose2 openproblems -v
        coveralls

    - name: Upload check results on fail
      if: failure()
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.config.name }}_results
        path: check
